name = {{main/ns}} PROD logging config file
# The status is the logging level for log4j2 itself.  WARN is the default.
status = WARN
monitorInterval = 5

rootLogger.level = WARN
rootLogger.appenderRef.console.ref = ConsoleAppender

appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %date %level %logger %message%n%throwable

logger.{{main/ns}}.name = {{top/ns}}.{{main/ns}}
logger.{{main/ns}}.level = WARN
logger.{{main/ns}}.additivity = false
logger.{{main/ns}}.appenderRef.console.ref = ConsoleAppender
